### ISSUE TITLE
Allow specifying version to get_article_details and list_files

### ISSUE THREAD

**Issue by dhimmel** [cognoma/figshare#3]
Regarding [`get_article_details`](https://github.com/cognoma/figshare/blob/661f8bad3385831588d79f7aef9d71b144fd2f1b/figshare/figshare.py#L184-L203) and [`list_files`](https://github.com/cognoma/figshare/blob/661f8bad3385831588d79f7aef9d71b144fd2f1b/figshare/figshare.py#L205-L225), it would be great to add a version parameter.

The default (`version=None`) would retrieve the latest version.

@vasudevanv does this make sense to you? And do you want to implement this?

**Comment by dhimmel** [comment]
You can get the the versioned article details with for example https://api.figshare.com/v2/articles/3487685/versions/1.

**Comment by vasudevanv** [comment]
Yeah absolutely. I can implement this. Will send a PR.

**Comment by wisygig** [comment]
@vasudevanv What's the status on this? If your swamped, I can take a stab at it.

**Comment by vasudevanv** [comment]
@wisygig take a shot. Have been swamped the last few weeks.
