### ISSUE TITLE
Download all files from a figshare article

### ISSUE THREAD

**Issue by dhimmel** [cognoma/figshare#4]
See this [legacy code](https://github.com/cognoma/cognoml/blob/f9669edfe0871cd161ffefa3409f67c98dd407a2/cognoml/figshare.py#L16-L61) from `cognoml`. It allows you to download all files from a figshare article.

This will be a useful feature to have.

**Comment by dhimmel** [comment]
@vasudevanv this doesn't necessarily have to be part of the main Figshare class. I could see it as a separate function in a utilities module. What do you think?

**Comment by vasudevanv** [comment]
I think it might be useful to have it in the main class itself.

**Comment by astrochun** [comment]
I was thinking similarly of having a function in the main Figshare class.

**Comment by astrochun** [comment]
Please take a look at this feature branch on ualibrary forked repo:
https://github.com/ualibraries/figshare/tree/feature/retrieve_files_from_article

I utilized your existing Figshare.list_files() to retrieve the URLs and filenames.

There are certainly multiple ways to retrieve data.  I went with using the standard `request` library.  Particularly following this guide:
https://www.codementor.io/aviaryan/downloading-files-from-urls-in-python-77q3bs0un

I have tested it out and it works:
```
from figshare.figshare import Figshare                                                      
fs = Figshare()                                                                             
article_id = 4757131                                                                        
fs.retrieve_files_from_article(article_id)          
```
If you like, I can submit another pull request.  

Some other things I would like to add would be a checksum inspection, and some logging details to indicate that the data retrieval is complete.

**Comment by dhimmel** [comment]
> If you like, I can submit another pull request.

Yes that would be great! You will probably want to support allowing the user to specify a destination directory for the downloaded files.
